# Generated by Django 5.2 on 2026-08-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary_type',
            field=models.CharField(choices=[('hourly', 'Per Hour'), ('daily', 'Per Day'), ('weekly', 'Per Week'), ('biweekly', 'Per Two Weeks'), ('monthly', 'Per Month'), ('quarterly', 'Per Quarter'), ('annually', 'Per Year')], default='annually', max_length=20),
        ),
    ]
