# Generated by Django 4.2.7 on 2026-06-21 17:29

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of appearance')),
                ('is_active', models.BooleanField(default=True, help_text='Show/Hide this FAQ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('about_title', models.CharField(max_length=200)),
                ('about_description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('mission', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('vision', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('google_map_embed', models.TextField(blank=True, help_text='Google Maps embed URL')),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('primary_color', models.CharField(default='#0d6efd', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', max_length=7)),
                ('footer_text', models.TextField(blank=True)),
                ('copyright_text', models.CharField(default='© 2024 Job Portal. All rights reserved.', max_length=255)),
                ('custom_css', models.TextField(blank=True, help_text='Custom CSS code')),
                ('custom_js', models.TextField(blank=True, help_text='Custom JavaScript code')),
                ('google_analytics', models.CharField(blank=True, help_text='Google Analytics tracking ID', max_length=50)),
                ('why_choose_us_title', models.CharField(default='Why Choose Us', max_length=200)),
                ('why_choose_us_subtitle', models.CharField(default='Why We Are the Right Choice', max_length=200)),
                ('why_choose_us_description', models.TextField(blank=True, default='We connect employers and job seekers through a smart, efficient, and reliable hiring platform.')),
                ('faq_title', models.CharField(default='Frequently Asked Questions', max_length=200)),
                ('faq_subtitle', models.CharField(blank=True, default='Find answers to common questions', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='fas fa-star', help_text='Font Awesome icon class (e.g., fas fa-users)', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of appearance')),
                ('is_active', models.BooleanField(default=True, help_text='Show/Hide this feature')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Why Choose Us Feature',
                'verbose_name_plural': 'Why Choose Us Features',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
