# Generated by Django 4.2.7 on 2026-08-18 17:40

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly name (e.g., terms-and-conditions)', unique=True)),
                ('page_type', models.CharField(choices=[('terms', 'Terms and Conditions'), ('privacy', 'Privacy Policy'), ('cookies', 'Cookie Policy'), ('about', 'About Us'), ('disclaimer', 'Disclaimer'), ('refund', 'Refund Policy')], max_length=20, unique=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Show/Hide this page')),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description')),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO meta keywords', max_length=255)),
            ],
            options={
                'verbose_name': 'Legal Page',
                'verbose_name_plural': 'Legal Pages',
                'ordering': ['page_type'],
            },
        ),
    ]
